# Generated by Django 5.0.4 on 2025-03-24 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.RemoveField(
            model_name='recycleform',
            name='organisation_id',
        ),
        migrations.RemoveField(
            model_name='recycleform',
            name='user_id',
        ),
        migrations.AddField(
            model_name='recycleform',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.owner'),
        ),
        migrations.AddField(
            model_name='recycleform',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.enduser'),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='phone_number',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='enduser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='enduser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='enduser',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='index_gmails',
            name='emails',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='owner',
            name='city',
            field=models.CharField(blank=True, default='', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='state',
            field=models.CharField(blank=True, default='', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='street',
            field=models.CharField(blank=True, default='', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='zipcode',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='payments',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='qna',
            name='answers',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='recycleform',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='recycleform',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recycleform',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recycle_images/'),
        ),
        migrations.AlterField(
            model_name='recycleform',
            name='item_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recycleform',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='recycleform',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='recycleform',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
