# Generated by Django 5.0.4 on 2025-03-26 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_delete_login_remove_recycleform_organisation_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enduser',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/'),
        ),
    ]
