# Generated by Django 5.0.4 on 2025-03-27 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_alter_notification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recycleform',
            name='weight',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
