# Generated by Django 5.0.4 on 2025-03-30 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_payments_created_payments_owner_alter_payments_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myApp.owner'),
        ),
    ]
