# Generated by Django 5.0.4 on 2025-03-30 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0009_alter_payments_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='transaction_id',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
